-- =====================================================
-- Description: Snowflake Infrastructure Setup for Terraform (PROD)
-- Target: Production Environment
-- Author: Project Admin
-- =====================================================

-- 1. Terraform execution role/user
-- -----------------------------------------------------
CREATE ROLE IF NOT EXISTS PROD_TF_ADMIN_ROLE;

CREATE USER IF NOT EXISTS PROD_TFRUNNER_USER
  RSA_PUBLIC_KEY='<YOUR_PROD_RSA_PUBLIC_KEY_HERE>'
  DEFAULT_ROLE=PROD_TF_ADMIN_ROLE;

GRANT ROLE PROD_TF_ADMIN_ROLE TO USER PROD_TFRUNNER_USER;

-- Grant privileges required for Terraform automation
GRANT CREATE DATABASE, CREATE WAREHOUSE, CREATE ROLE, CREATE USER, MANAGE GRANTS
  ON ACCOUNT TO ROLE PROD_TF_ADMIN_ROLE;

-- Grant to SYSADMIN for governance/visibility
GRANT ROLE PROD_TF_ADMIN_ROLE TO ROLE SYSADMIN;

-- 2. Data layer databases/schemas
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS PROD_BRONZE_DB;
ALTER DATABASE PROD_BRONZE_DB SET DATA_RETENTION_TIME_IN_DAYS = 90;
CREATE SCHEMA   IF NOT EXISTS PROD_BRONZE_DB.RAW_DATA WITH MANAGED ACCESS;
ALTER SCHEMA PROD_BRONZE_DB.RAW_DATA ENABLE MANAGED ACCESS;

CREATE DATABASE IF NOT EXISTS PROD_SILVER_DB;
ALTER DATABASE PROD_SILVER_DB SET DATA_RETENTION_TIME_IN_DAYS = 90;
CREATE SCHEMA   IF NOT EXISTS PROD_SILVER_DB.CLEANSED WITH MANAGED ACCESS;
ALTER SCHEMA PROD_SILVER_DB.CLEANSED ENABLE MANAGED ACCESS;

CREATE DATABASE IF NOT EXISTS PROD_GOLD_DB;
ALTER DATABASE PROD_GOLD_DB SET DATA_RETENTION_TIME_IN_DAYS = 90;
CREATE SCHEMA   IF NOT EXISTS PROD_GOLD_DB.MARKETING_MART WITH MANAGED ACCESS;
ALTER SCHEMA PROD_GOLD_DB.MARKETING_MART ENABLE MANAGED ACCESS;

-- 2.1 Network policy for Terraform execution
-- -----------------------------------------------------
CREATE NETWORK POLICY IF NOT EXISTS PROD_TERRAFORM_NETWORK_POLICY
  ALLOWED_IP_LIST = ('<HCP_TERRAFORM_CIDR_1>', '<CORPORATE_CIDR_1>');

ALTER USER PROD_TFRUNNER_USER SET NETWORK_POLICY = PROD_TERRAFORM_NETWORK_POLICY;

-- 3. Transfer DB ownership to PROD_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON DATABASE PROD_BRONZE_DB TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE PROD_SILVER_DB TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE PROD_GOLD_DB TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;

-- 3.1 Transfer schema ownership to PROD_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON SCHEMA PROD_BRONZE_DB.RAW_DATA TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_SILVER_DB.CLEANSED TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_GOLD_DB.MARKETING_MART TO ROLE PROD_TF_ADMIN_ROLE COPY CURRENT GRANTS;
