-- =====================================================
-- Description: Snowflake Infrastructure Setup for Terraform (DEV)
-- Target: Development Environment
-- Author: Project Admin
-- =====================================================

-- 1. Terraform execution role/user
-- -----------------------------------------------------
CREATE ROLE IF NOT EXISTS DEV_TF_ADMIN_ROLE;

CREATE USER IF NOT EXISTS DEV_TFRUNNER_USER
  RSA_PUBLIC_KEY='<YOUR_DEV_RSA_PUBLIC_KEY_HERE>'
  DEFAULT_ROLE=DEV_TF_ADMIN_ROLE;

GRANT ROLE DEV_TF_ADMIN_ROLE TO USER DEV_TFRUNNER_USER;

-- Grant privileges required for Terraform automation
GRANT CREATE DATABASE, CREATE WAREHOUSE, CREATE ROLE, CREATE USER, MANAGE GRANTS
  ON ACCOUNT TO ROLE DEV_TF_ADMIN_ROLE;

-- Grant to SYSADMIN for governance/visibility
GRANT ROLE DEV_TF_ADMIN_ROLE TO ROLE SYSADMIN;

-- 2. Data layer databases/schemas
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS DEV_BRONZE_DB;
ALTER DATABASE DEV_BRONZE_DB SET DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA   IF NOT EXISTS DEV_BRONZE_DB.RAW_DATA WITH MANAGED ACCESS;
ALTER SCHEMA DEV_BRONZE_DB.RAW_DATA ENABLE MANAGED ACCESS;

CREATE DATABASE IF NOT EXISTS DEV_SILVER_DB;
ALTER DATABASE DEV_SILVER_DB SET DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA   IF NOT EXISTS DEV_SILVER_DB.CLEANSED WITH MANAGED ACCESS;
ALTER SCHEMA DEV_SILVER_DB.CLEANSED ENABLE MANAGED ACCESS;

CREATE DATABASE IF NOT EXISTS DEV_GOLD_DB;
ALTER DATABASE DEV_GOLD_DB SET DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA   IF NOT EXISTS DEV_GOLD_DB.MARKETING_MART WITH MANAGED ACCESS;
ALTER SCHEMA DEV_GOLD_DB.MARKETING_MART ENABLE MANAGED ACCESS;

-- 2.1 Network policy for Terraform execution
-- -----------------------------------------------------
CREATE NETWORK POLICY IF NOT EXISTS DEV_TERRAFORM_NETWORK_POLICY
  ALLOWED_IP_LIST = ('<HCP_TERRAFORM_CIDR_1>', '<CORPORATE_CIDR_1>');

ALTER USER DEV_TFRUNNER_USER SET NETWORK_POLICY = DEV_TERRAFORM_NETWORK_POLICY;

-- 3. Transfer DB ownership to DEV_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON DATABASE DEV_BRONZE_DB TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE DEV_SILVER_DB TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE DEV_GOLD_DB TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;

-- 3.1 Transfer schema ownership to DEV_TF_ADMIN_ROLE
-- -----------------------------------------------------
GRANT OWNERSHIP ON SCHEMA DEV_BRONZE_DB.RAW_DATA TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA DEV_SILVER_DB.CLEANSED TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA DEV_GOLD_DB.MARKETING_MART TO ROLE DEV_TF_ADMIN_ROLE COPY CURRENT GRANTS;
